In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


Data Preprocessing

----> Training image Preprocessing

In [3]:
training_set = tf.keras.utils.image_dataset_from_directory(
    r'D:\Smart Agriculture disease detection\archive\New Plant Diseases Dataset(Augmented)\New Plant Diseases Dataset(Augmented)\train',
    labels="inferred",
    label_mode="categorical",
    color_mode="rgb",
    batch_size=32,
    image_size=(128,128),
    shuffle=True
)

Found 70295 files belonging to 38 classes.


----> Validation Image Preprocessing


In [5]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    r'D:\Smart Agriculture disease detection\archive\New Plant Diseases Dataset(Augmented)\New Plant Diseases Dataset(Augmented)\valid',
    labels="inferred",
    label_mode="categorical",
    color_mode="rgb",
    batch_size=32,
    image_size=(128,128),
    shuffle=True
)

Found 17572 files belonging to 38 classes.


In [7]:
for x, y in training_set:
    print(x, x.shape)
    print(y, y.shape)
    break

tf.Tensor(
[[[[112.   109.   130.  ]
   [111.25 108.25 129.25]
   [119.   116.   137.  ]
   ...
   [152.5  153.5  173.5 ]
   [154.   155.   175.  ]
   [161.25 162.25 182.25]]

  [[115.75 112.75 133.75]
   [114.   111.   132.  ]
   [127.5  124.5  145.5 ]
   ...
   [152.   153.   173.  ]
   [154.25 155.25 175.25]
   [159.25 160.25 180.25]]

  [[110.   107.   128.  ]
   [119.   116.   137.  ]
   [132.25 129.25 150.25]
   ...
   [150.   151.   171.  ]
   [152.75 153.75 173.75]
   [155.   156.   176.  ]]

  ...

  [[ 10.5    6.     8.5 ]
   [  8.5    3.5    7.5 ]
   [ 12.75   7.75  12.25]
   ...
   [124.75 122.75 136.75]
   [124.25 122.25 136.25]
   [136.   134.   148.  ]]

  [[ 13.     8.    14.  ]
   [ 10.5    5.5   11.5 ]
   [ 11.75   6.75  13.5 ]
   ...
   [125.75 123.75 137.75]
   [120.75 118.75 132.75]
   [131.25 129.25 143.25]]

  [[ 14.25   9.25  16.25]
   [ 25.5   20.5   27.5 ]
   [ 62.    56.    66.  ]
   ...
   [128.75 126.75 140.75]
   [128.   126.   140.  ]
   [128.75 126.75 14

Building Model

In [19]:
from tensorflow.keras.layers import Conv2D, MaxPooling2D,Flatten
from tensorflow.keras import Sequential

In [20]:
model = Sequential()

In [21]:
model.add(Conv2D(filters=32, kernel_size=3, padding='same', activation='relu', input_shape=[128,128,3]))
model.add(Conv2D(filters=32, kernel_size=3, padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=2, strides=2))

In [22]:
model.add(Conv2D(filters=32, kernel_size=3, padding='same', activation='relu', input_shape=[128,128,3]))
model.add(Conv2D(filters=32, kernel_size=3, padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=2, strides=2))

In [23]:
model.add(Conv2D(filters=32, kernel_size=3, padding='same', activation='relu', input_shape=[128,128,3]))
model.add(Conv2D(filters=32, kernel_size=3, padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=2, strides=2))

In [24]:
model.add(Conv2D(filters=32, kernel_size=3, padding='same', activation='relu', input_shape=[128,128,3]))
model.add(Conv2D(filters=32, kernel_size=3, padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=2, strides=2))

Till now we do Convolutional operation and MaxPooling operation

Now Flatting the layer

In [25]:
model.add(Flatten())

In [26]:
model.add(Dense(units=1024,activation='relu')) 
# Dense it nothing but hidden layer and unit is how many neurons we need in dense layer

In [27]:
# Output Layer
model.add(Dense(units=38,activation='softmax'))

Compiling Model

In [28]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])  

In [29]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_12 (Conv2D)              │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_13 (Conv2D)              │ (None, 128, 128, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 64, 64, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_14 (Conv2D)              │ (None, 64, 64, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_15 (Conv2D)              │ (None, 64, 64, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_5 (MaxPooling2D)  │ (None, 32, 32, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_16 (Conv2D)              │ (None, 32, 32, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_17 (Conv2D)              │ (None, 32, 32, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_6 (MaxPooling2D)  │ (None, 16, 16, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_18 (Conv2D)              │ (None, 16, 16, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_19 (Conv2D)              │ (None, 16, 16, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_7 (MaxPooling2D)  │ (None, 8, 8, 32)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1024)           │     2,098,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 38)             │        38,950 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,202,758 (8.40 MB)

 Trainable params: 2,202,758 (8.40 MB)

 Non-trainable params: 0 (0.00 B)